[package]
name = "shine-render-gl-derive"
version = "0.1.0"
authors = ["gzp <z.p.gaal.devel@gmail.com>"]
license = "MIT/Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "*"
proc-macro2 = { version = "*", features = ["nightly"] }
quote = "*"
