.cargo_build_template: &cargo_build
  stage: build  
  script:
    - cargo build --verbose

.cargo_test_template: &cargo_test
  stage: test  
  script:
    - cargo test --verbose --jobs 1 -p shine-stdext -- --test-threads=1
    - cargo test --verbose --jobs 1 -p shine-graph
    - cargo test --verbose --jobs 1 -p shine-ecs -- --test-threads=1
    - cargo test --verbose --jobs 1 -p shine-gltf
    - cargo test --verbose --jobs 1 -p shine-math    

nightly:cargo:
  image: rustdocker/rust:nightly
  #<<: *cargo_build
  <<: *cargo_test