environment:
  matrix:
  - TARGET: nightly-x86_64-pc-windows-msvc
  - TARGET: nightly-i686-pc-windows-msvc
  - TARGET: nightly-x86_64-pc-windows-gnu
  - TARGET: nightly-i686-pc-windows-gnu
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - ps: $env:RUST_TEST_THREADS=1
  - rustc -vV
  - cargo -vV
build_script:
  - cargo build
  - cargo build -p shine-store --tests
  - cargo build -p shine-graph --tests
test_script:
  - cargo test -p shine-store
  - cargo test -p shine-graph
