[package]
name = "shine"
version = "0.1.0"
authors = ["gzp <z.p.gaal.devel@gmail.com>"]

[dependencies]
shine-store = {path = "store"}
shine-render-core = {path = "render-core"}
shine-render-gl = {path = "render-gl"}
shine-render = {path = "render"}


# for examples
rayon = "*"
image = "*"
nalgebra = "*"
time = "*"


[[example]]
name = "cubes"
path = "examples/cubes/cubes.rs"

[[example]]
name = "hello"
path = "examples/hello/hello.rs"