[package]
name = "shine"
version = "0.1.0"
authors = ["gzp <z.p.gaal.devel@gmail.com>"]
license = "MIT/Apache-2.0"
description = "General purpose multi-threaded sanbox engine."
repository = "https://github.com/gzp/shine"
keywords = ["component system", "game"]

[workspace]
members = [ "tools", "store", "graph", "graph-macro" ]

[dependencies]
log = "*"

shine-store = {path = "store"}
shine-graph = {path = "graph"}
shine-graph-macro = {path = "graph-macro"}
shine-tools = {path = "tools"}
#shine-ecs = {path = "ecs"}

#[dev-dependencies] https://github.com/rust-lang/cargo/issues/860
#env_logger = "*"

env_logger = "*"
rand = "*"
permutohedron = "*"
