[package]
name = "shine"
version = "0.1.0"
authors = ["gzp <z.p.gaal.devel@gmail.com>"]
license = "MIT/Apache-2.0"
description = "General purpose multi-threaded sanbox engine."
repository = "https://github.com/gzp/shine"
keywords = ["component system", "game"]

[workspace]
members = [ "testutils", "store", "graph", "graph-macro", "ecs" ]

[dependencies]
log = "*"
env_logger = "*"

shine-store = {path = "store"}
shine-ecs = {path = "ecs"}
