[package]
name = "shine-store"
version = "0.1.1"
authors = ["gzp <z.p.gaal.devel@gmail.com>"]
license = "MIT/Apache-2.0"
description = "SHINE. Storage and container module of a general purpose multi-threaded rendering engine."
repository = "https://github.com/zpgaal/shine"
keywords = ["shine", "render", "opengl", "game"]

[dependencies]
libc = "0.2.36"
lazy_static = "1.0.0"
num_cpus="1.8.0"
