[package]
name = "shine-render-derive"
version = "0.1.0"
authors = ["gzp <z.p.gaal.devel@gmail.com>"]
license = "MIT/Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "0.12"
proc-macro2 = { version = "0.2", features = ["nightly"] }
quote = "0.4"
